server:
  port: 8079

spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://47.111.115.226:3306/test?serverTimezone=GMT%2B8&amp&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ffcs_rp
    test2:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: scott
      password: 1234



